INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(1,'ANDORRA','AD','AND','043',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(2,'EMIRATOS ARABES UNIDOS','AE','ARE','647',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(3,'AFGANISTAN','AF','AFG','660',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(4,'ANTIGUA Y BARBUDA','AG','ATG','459',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(5,'ANGUILA','AI','AIA','446',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(6,'ALBANIA','AL','ALB','070',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(7,'ARMENIA','AM','ARM','077',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(8,'ANTILLAS NEERLANDESAS','AN','ANT','478',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(9,'ANGOLA','AO','AGO','330',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(10,'ANTARTIDA','AQ','','891',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(11,'ARGENTINA','AR','ARG','528',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(12,'SAMOA AMERICANA','AS','ASM','830',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(13,'AUSTRIA','AT','AUT','038',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(14,'AUSTRALIA','AU','AUS','800',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(15,'ARUBA','AW','ABW','474',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(16,'AZERBAIYAN','AZ','AZE','078',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(17,'BOSNIA-HERZEGOVINA','BA','BIH','093',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(18,'BARBADOS','BB','BRB','469',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(19,'BANGLADESH','BD','BGD','666',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(20,'BELGICA','BE','BEL','017',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(21,'BURKINA FASO','BF','BFA','236',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(22,'BULGARIA','BG','BGR','068',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(23,'BAHREIN','BH','BHR','640',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(24,'BURUNDI','BI','BDI','328',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(25,'BENIN','BJ','BEN','284',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(26,'BERMUDAS','BM','BMU','413',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(27,'BRUNEI','BN','BRN','703',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(28,'BOLIVIA','BO','BOL','516',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(29,'PAISES BAJOS (PARTE CARIBEÑA)','BQ','','535',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(30,'BRASIL','BR','BRA','508',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(31,'BAHAMAS','BS','BHS','453',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(32,'BUTAN','BT','BTN','675',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(33,'BOUVET, ISLA','BV','BVT','892',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(34,'BOTSUANA','BW','BWA','391',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(35,'BIELORRUSIA','BY','BLR','073',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(36,'BELICE','BZ','BLZ','421',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(37,'CANADA','CA','CAN','404',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(38,'COCOS','CC','CCK','833',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(39,'CONGO, REPUBLICA DEMOCRATICA','CD','COD','322',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(40,'CENTROAFRICANA, REPUBLICA','CF','CAF','306',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(41,'CONGO','CG','COG','318',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(42,'SUIZA','CH','CHE','039',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(43,'COSTA DE MARFIL','CI','CIV','272',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(44,'COOK, ISLAS','CK','COK','107',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(45,'CHILE','CL','CHL','512',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(46,'CAMERUN','CM','CMR','302',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(47,'CHINA','CN','CHN','720',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(48,'COLOMBIA','CO','COL','480',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(49,'COSTA RICA','CR','CRI','436',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(50,'CUBA','CU','CUB','448',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(51,'CABO VERDE, REPUBLICA DE','CV','CPV','247',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(52,'CURAÇAO','CW','CUW','531',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(53,'NAVIDAD, ISLA','CX','CXR','834',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(54,'CHIPRE','CY','CYP','600',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(55,'CHECA, REPUBLICA','CZ','CZE','061',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(56,'ALEMANIA','DE','DEU','004',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(57,'YIBUTI','DJ','DJI','338',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(58,'DINAMARCA','DK','DNK','008',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(59,'DOMINICA','DM','DMA','460',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(60,'DOMINICANA, REPUBLICA','DO','DOM','456',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(61,'ARGELIA','DZ','DZA','208',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(62,'ECUADOR','EC','ECU','500',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(63,'ESTONIA','EE','EST','053',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(64,'EGIPTO','EG','EGY','220',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(65,'SAHARA OCCIDENTAL','EH','ESH','732',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(66,'ERITREA','ER','ERI','336',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(67,'ESPAÑA','ES','ESP','011',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(68,'ETIOPIA','ET','ETH','334',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(69,'FINLANDIA','FI','FIN','032',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(70,'FIYI','FJ','FJI','815',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(71,'MALVINAS, ISLAS','FK','FLK','529',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(72,'MICRONESIA','FM','FSM','823',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(73,'FEROE, ISLAS','FO','FRO','041',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(74,'FRANCIA','FR','FRA','001',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(75,'GABON','GA','GAB','314',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(76,'REINO UNIDO','GB','GBR','006',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(77,'GRANADA','GD','GRD','473',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(78,'GEORGIA','GE','GEO','076',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(79,'GUERNESEY','GG','GGY','108',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(80,'GHANA','GH','GHA','276',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(81,'GIBRALTAR','GI','GIB','044',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(82,'GROENLANDIA','GL','GRL','406',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(83,'GAMBIA','GM','GMB','252',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(84,'GUINEA','GN','GIN','260',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(85,'GUINEA ECUATORIAL','GQ','GNQ','310',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(86,'GRECIA','GR','GRC','009',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(87,'GEORGIA DEL SUR','GS','SGS','893',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(88,'GUATEMALA','GT','GTM','416',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(89,'GUAM','GU','GUM','831',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(90,'GUINEA-BISSAU','GW','GNB','257',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(91,'GUYANA','GY','GUY','488',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(92,'HONG-KONG','HK','HKG','740',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(93,'HEARD Y MCDONALD, ISLAS','HM','HMD','835',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(94,'HONDURAS','HN','HND','424',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(95,'CROACIA','HR','HRV','092',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(96,'HAITI','HT','HTI','452',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(97,'HUNGRIA','HU','HUN','064',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(98,'INDONESIA','ID','IDN','700',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(99,'IRLANDA','IE','IRL','007',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(100,'ISRAEL','IL','ISR','624',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(101,'ISLA DE MAN','IM','IMN','104',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(102,'INDIA','IN','IND','664',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(103,'OCEANO INDICO, TERRI.BRITANICO','IO','IOT','357',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(104,'IRAQ','IQ','IRQ','612',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(105,'IRAN','IR','IRN','616',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(106,'ISLANDIA','IS','ISL','024',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(107,'ITALIA','IT','ITA','005',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(108,'JERSEY','JE','JEY','109',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(109,'JAMAICA','JM','JAM','464',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(110,'JORDANIA','JO','JOR','628',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(111,'JAPON','JP','JPN','392',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(112,'KENIA','KE','KEN','346',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(113,'KIRGUISTAN','KG','KGZ','083',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(114,'CAMBOYA','KH','KHM','696',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(115,'KIRIBATI','KI','KIR','812',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(116,'COMORAS','KM','COM','375',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(117,'SAN CRISTOBAL Y NIEVES','KN','KNA','449',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(118,'COREA DEL NORTE','KP','PRK','724',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(119,'COREA DEL SUR','KR','KOR','728',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(120,'KUWAIT','KW','KWT','636',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(121,'CAIMAN, ISLAS','KY','CYM','463',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(122,'KAZAJSTAN','KZ','KAZ','079',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(123,'LAOS','LA','LAO','684',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(124,'LIBANO','LB','LBN','604',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(125,'SANTA LUCIA','LC','LCA','465',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(126,'LIECHTENSTEIN','LI','LIE','037',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(127,'SRI LANKA','LK','LKA','669',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(128,'LIBERIA','LR','LBR','268',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(129,'LESOTHO','LS','LSO','395',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(130,'LITUANIA','LT','LTU','055',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(131,'LUXEMBURGO','LU','LUX','018',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(132,'LETONIA','LV','LVA','054',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(133,'LIBIA','LY','LBY','216',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(134,'MARRUECOS','MA','MAR','204',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(135,'MONACO','MC','MCO','101',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(136,'MOLDAVIA','MD','MDA','074',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(137,'MONTENEGRO','ME','MNE','499',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(138,'MADAGASCAR','MG','MDG','370',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(139,'MARSHALL, ISLAS','MH','MHL','824',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(140,'MACEDONIA','MK','MKD','096',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(141,'MALI','ML','MLI','232',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(142,'MYANMAR','MM','MMR','676',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(143,'MONGOLIA','MN','MNG','716',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(144,'MACAO','MO','MAC','743',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(145,'MARIANAS DEL NORTE, ISLAS','MP','MNP','820',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(146,'MAURITANIA','MR','MRT','228',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(147,'MONTSERRAT','MS','MSR','470',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(148,'MALTA','MT','MLT','046',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(149,'MAURICIO','MU','MUS','373',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(150,'MALDIVAS','MV','MDV','667',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(151,'MALAWI','MW','MWI','386',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(152,'MEXICO','MX','MEX','412',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(153,'MALASIA','MY','MYS','701',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(154,'MOZAMBIQUE','MZ','MOZ','366',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(155,'NAMIBIA','NA','NAM','389',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(156,'NUEVA CALEDONIA','NC','NCL','809',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(157,'NIGER','NE','NER','240',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(158,'NORFOLK, ISLA','NF','NFK','836',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(159,'NIGERIA','NG','NGA','288',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(160,'NICARAGUA','NI','NIC','432',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(161,'PAISES BAJOS','NL','NLD','003',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(162,'NORUEGA','NO','NOR','028',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(163,'NEPAL','NP','NPL','672',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(164,'NAURU','NR','NRU','803',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(165,'NIUE, ISLA','NU','NIU','838',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(166,'NUEVA ZELANDA','NZ','NZL','804',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(167,'OMAN','OM','OMN','649',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(168,'PANAMA','PA','PAN','442',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(169,'PERU','PE','PER','504',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(170,'POLINESIA FRANCESA','PF','PYF','822',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(171,'PAPUA NUEVA GUINEA','PG','PNG','801',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(172,'FILIPINAS','PH','PHL','708',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(173,'PAKISTAN','PK','PAK','662',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(174,'POLONIA','PL','POL','060',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(175,'SAN PEDRO Y MIQUELON','PM','SPM','408',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(176,'PITCAIRN','PN','PCN','813',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(177,'PUERTO RICO','PR','PRI','401',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(178,'TERRITORIO PALESTINO OCUPADO','PS','PSE','627',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(179,'PORTUGAL','PT','PRT','010',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(180,'PALAU','PW','PLW','825',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(181,'PARAGUAY','PY','PRY','520',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(182,'QATAR','QA','QAT','644',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(183,'OTROS PAISES NO RELACIONADOS','QU','','958',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(184,'RUMANIA','RO','ROU','066',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(185,'SERBIA','RS','SRB','688',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(186,'RUSIA','RU','RUS','075',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(187,'RUANDA','RW','RWA','324',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(188,'ARABIA SAUDI','SA','SAU','632',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(189,'SALOMON, ISLAS','SB','SLB','806',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(190,'SEYCHELLES','SC','SYC','355',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(191,'SUDAN','SD','SDN','224',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(192,'SUECIA','SE','SWE','030',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(193,'SINGAPUR','SG','SGP','706',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(194,'SANTA ELENA','SH','SHN','329',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(195,'ESLOVENIA','SI','SVN','091',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(196,'ESLOVAQUIA','SK','SVK','063',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(197,'SIERRA LEONA','SL','SLE','264',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(198,'SAN MARINO','SM','SMR','047',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(199,'SENEGAL','SN','SEN','248',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(200,'SOMALIA','SO','SOM','342',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(201,'SURINAM','SR','SUR','492',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(202,'SUDAN DEL SUR','SS','SSD','730',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(203,'SANTO TOME Y PRINCIPE','ST','STP','311',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(204,'SALVADOR, EL','SV','SLV','428',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(205,'SAN MARTIN','SX','','663',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(206,'SIRIA','SY','SYR','608',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(207,'SUAZILANDIA','SZ','SWZ','393',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(208,'TURCAS Y CAICOS, ISLAS','TC','TCA','454',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(209,'CHAD','TD','TCD','244',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(210,'TIERRAS AUSTRALES FRANCESAS','TF','ATF','894',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(211,'TOGO','TG','TGO','280',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(212,'TAILANDIA','TH','THA','680',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(213,'TAYIKISTAN','TJ','TJK','082',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(214,'TOKELAU, ISLAS','TK','TKL','839',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(215,'TIMOR LESTE','TL','TLS','626',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(216,'TURKMENISTAN','TM','TKM','080',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(217,'TUNEZ','TN','TUN','212',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(218,'TONGA','TO','TON','817',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(219,'TURQUIA','TR','TUR','052',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(220,'TRINIDAD Y TOBAGO','TT','TTO','472',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(221,'TUVALU','TV','TUV','807',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(222,'TAIWAN','TW','TWN','736',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(223,'TANZANIA','TZ','TZA','352',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(224,'UCRANIA','UA','UKR','072',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(225,'UGANDA','UG','UGA','350',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(226,'MENORES ALEJADAS DE EE.UU, ISLAS','UM','','832',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(227,'ESTADOS UNIDOS DE AMERICA','US','USA','400',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(228,'URUGUAY','UY','URY','524',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(229,'UZBEKISTAN','UZ','UZB','081',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(230,'VATICANO, CIUDAD DEL','VA','VAT','045',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(231,'SAN VICENTE Y LAS GRANADINAS','VC','VCT','467',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(232,'VENEZUELA','VE','VEN','484',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(233,'VIRGENES BRITANICAS, ISLAS','VG','VGB','468',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(234,'VIRGENES DE LOS EE.UU, ISLAS','VI','VIR','457',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(235,'VIETNAM','VN','VNM','690',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(236,'VANUATU','VU','VUT','816',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(237,'WALLIS Y FUTUNA, ISLAS','WF','WLF','811',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(238,'SAMOA','WS','WSM','819',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(239,'YEMEN','YE','YEM','653',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(240,'MAYOTTE','YT','MYT','377',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(241,'SUDAFRICA','ZA','ZAF','388',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(242,'ZAMBIA','ZM','ZMB','378',sysdate,sysdate);
INSERT INTO dir_pais(id_pais, nombre, codigo_iso2, codigo_iso3, codigo_uni, fecha_creacion, fecha_modificacion) VALUES(243,'ZIMBABUE','ZW','ZWE','382',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(1,01,'ARABA/ALAVA',15,'PAIS VASCO',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(2,02,'ALBACETE',07,'CASTILLA LA MANCHA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(3,03,'ALICANTE',17,'VALENCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(4,04,'ALMERIA',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(5,05,'AVILA',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(6,06,'BADAJOZ',10,'EXTREMADURA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(7,07,'I. BALEARS',04,'ILLES BALEARS',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(8,08,'BARCELONA',09,'CATALUÑA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(9,09,'BURGOS',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(10,10,'CACERES',10,'EXTREMADURA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(11,11,'CADIZ',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(12,12,'CASTELLON',17,'VALENCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(13,13,'CIUDAD REAL',07,'CASTILLA LA MANCHA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(14,14,'CORDOBA',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(15,15,'A CORUÑA',11,'GALICIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(16,16,'CUENCA',07,'CASTILLA LA MANCHA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(17,17,'GIRONA',09,'CATALUÑA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(18,18,'GRANADA',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(19,19,'GUADALAJARA',07,'CASTILLA LA MANCHA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(20,20,'GIPUZKOA',15,'PAIS VASCO',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(21,21,'HUELVA',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(22,22,'HUESCA',02,'ARAGON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(23,23,'JAEN',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(24,24,'LEON',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(25,25,'LLEIDA',09,'CATALUÑA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(26,26,'LA RIOJA',16,'LA RIOJA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(27,27,'LUGO',11,'GALICIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(28,28,'MADRID',12,'MADRID',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(29,29,'MALAGA',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(30,30,'MURCIA',13,'MURCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(31,31,'NAVARRA',14,'NAVARRA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(32,32,'OURENSE',11,'GALICIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(33,33,'ASTURIAS',03,'PRINCIPADO DE ASTURIAS',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(34,34,'PALENCIA',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(35,35,'LAS PALMAS',05,'CANARIAS',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(36,36,'PONTEVEDRA',11,'GALICIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(37,37,'SALAMANCA',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(38,38,'SANTA CRUZ DE TENERIFE',05,'CANARIAS',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(39,39,'CANTABRIA',06,'CANTABRIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(40,40,'SEGOVIA',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(41,41,'SEVILLA',01,'ANDALUCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(42,42,'SORIA',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(43,43,'TARRAGONA',09,'CATALUÑA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(44,44,'TERUEL',02,'ARAGON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(45,45,'TOLEDO',07,'CASTILLA LA MANCHA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(46,46,'VALENCIA',17,'VALENCIA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(47,47,'VALLADOLID',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(48,48,'BIZKAIA',15,'PAIS VASCO',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(49,49,'ZAMORA',08,'CASTILLA Y LEON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(50,50,'ZARAGOZA',02,'ARAGON',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(51,51,'CEUTA',18,'CEUTA',sysdate,sysdate);
INSERT INTO dir_provincia(id_provincia, codigo_provincia, nombre, codigo_ca, nombre_ca, fecha_creacion, fecha_modificacion) VALUES(52,52,'MELILLA',19,'MELILLA',sysdate,sysdate);